### ISSUE TITLE
10 change request

### ISSUE THREAD

**Issue by nazim9919** [nazim9919/Software-Configuration-Management#1]
We need to complete the CR template for the manager and CCB part.
[CHANGE REQUEST FORM-BLANK (1).docx](https://github.com/nazim9919/Software-Configuration-Management/files/6201829/CHANGE.REQUEST.FORM-BLANK.1.docx)

**Comment by nazim9919** [comment]
@mimiatikah @adsofia please review the change request and give comments.

**Comment by adsofia** [comment]
Noted Nazim we will discuss in the meeting about the CRs.

**Comment by adsofia** [comment]
Then later will update in readme.md

**Comment by nazim9919** [comment]
all the CR already been finalized
